#!/bin/bash
# EWAM training launcher — LIBERO stage-2 finetune (lerobot data, dim16, horizontal, plain loss).
#
# Entry point : train/train_ewam.py           (plain flow-matching loss)
# Config      : configs/ewam_libero.yaml
# DeepSpeed   : configs/zero1.json (ZeRO stage 1, bf16)
#
# Data: LIBERO demonstrations in LeRobot format (one directory per suite, see README
#       "Data preparation → LIBERO"), with t5_embedding/ generated by
#       data/libero/regenerate_libero_t5_with_prefix.py.
#
# Usage:
#   bash scripts/train_ewam_libero.sh
#   # Override GPUs / port:
#   CUDA_VISIBLE_DEVICES=0,1,2,3 MASTER_PORT=29201 bash train_ewam_libero.sh
#   # Multi-node (torchrun):
#   NNODES=2 RANK=0 MASTER_ADDR=<ip> bash train_ewam_libero.sh

# cd to the package root (this script lives in scripts/)
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7} torchrun \
    --nnodes=${NNODES:-1} \
    --nproc_per_node=${NPROC_PER_NODE:-8} \
    --node_rank=${RANK:-0} \
    --master_addr=${MASTER_ADDR:-127.0.0.1} \
    --master_port=${MASTER_PORT:-29200} \
    train/train_ewam.py \
    --deepspeed configs/zero1.json \
    --config configs/ewam_libero.yaml
